function(add_linker_warnings theTarget)
    if(APPLE)
       # target_link_libraries(${theTarget} PRIVATE "-Wl,-fatal_warnings")
    endif()
endfunction()

function(add_linker_warnings_external theTarget)
  if(APPLE)
    target_link_libraries(${theTarget} PRIVATE -Wl,-undefined,dynamic_lookup)
  elseif(UNIX)
    if(LLD_LINKER_SUPPORTED)
      target_link_libraries(${theTarget} PRIVATE -Wl,--unresolved-symbols=report-all)
    else()
      target_link_libraries(${theTarget} PRIVATE -Wl,--warn-unresolved-symbols)
    endif()
  endif()
endfunction()
