function(use_gold theTarget)

  if(UNIX AND NOT APPLE)
    if(WL_ZDEFS_SUPPORTED)
      if(GOLD_LINKER_SUPPORTED)
        target_link_libraries(${theTarget} PRIVATE "-fuse-ld=gold" "-Wl,-z,defs")
      endif()
    endif()
  endif()
endfunction()
